#include <asm-generic/errno.h>
#include <iostream>
#include <errno.h>
using namespace std;
int main(){

	cout <<"EPERM           "<<EPERM<<"    : Operation not permitted."<<'\n';
	cout <<"ENOENT          "<<ENOENT<<"    : No such file or directory. "<<'\n';
	cout <<"ESRCH           "<<ESRCH<<"    : No such process."<<'\n';
	cout <<"EINTR           "<<EINTR<<"    : Interrupted function call. "<<'\n';
	cout <<"EIO             "<<EIO<<"    : I/O error. "<<'\n';
	cout <<"ENXIO           "<<ENXIO<<"    : No such device or address."<<'\n';
	cout <<"E2BIG           "<<E2BIG<<"    : Argument list too long."<<'\n';
	cout <<"ENOEXEC         "<<ENOEXEC<<"    : Executable file format error."<<'\n';
	cout <<"EBADF           "<<EBADF<<"    : Bad file descriptor. "<<'\n';
	cout <<"EBADMSG         "<<EBADF<<"    : Bad message. "<<'\n';
	cout <<"ECHILD          "<<ECHILD<<"   : No child processes. "<<'\n';
	cout <<"EAGAIN          "<<EAGAIN<<"   : Resource unavailable. try again (may be the same value as [EWOULDBLOCK])."<<'\n';
	cout <<"EWOULDBLOCK     "<<EWOULDBLOCK<<"   : Operation would block (may be the same value as [EAGAIN])."<<'\n';
	cout <<"ENOMEM          "<<ENOMEM<<"   : Not enough speace(memory)."<<'\n';
	cout <<"EACCES          "<<EACCES<<"   : Permission denied."<<'\n';
	cout <<"EFAULT          "<<EFAULT<<"   : Bad address. "<<'\n';
	cout <<"ENOTBLK         "<<ENOTBLK<<"   : Block device required. " <<'\n';
	cout <<"EBUSY           "<<EBUSY<<"   : Device of resource busy. "<<'\n';
	cout <<"EEXIST          "<<EEXIST<<"   : File exists. "<<'\n';
	cout <<"EXDEV           "<<EXDEV<<"   : Cross-device link."<<'\n';
	cout <<"ENODEV          "<<ENODEV<<"   : No such device. "<<'\n';
	cout <<"ENOTDIR         "<<ENOTDIR<<"   : Not a directory or a symbolic link to a directory."<<'\n';
	cout <<"EISDIR          "<<EISDIR<<"   : Is a directory. "<<'\n';
	cout <<"EINVAL          "<<EINVAL<<"   : Invalid argument. "<<'\n';
	cout <<"ENFILE          "<<ENFILE<<"   : Too many files open in system."<<'\n';
	cout <<"EMFILE          "<<EMFILE<<"   : File descriptor value too large. "<<'\n';
	cout <<"ENOTTY          "<<ENOTTY<<"   : Inappropriate I/O control operation."<<'\n'; 
	cout <<"ETXTBSY         "<<ETXTBSY<<"   : Text file busy."<<'\n';
	cout <<"EFBIG           "<<EFBIG<<"   : File too large. "<<'\n';
	cout <<"ENOSPC          "<<ENOSPC<<"   : No space left on device."<<'\n';
	cout <<"ESPIPE          "<<ESPIPE<<"   : Invaild seek. "<<'\n'; 
	cout <<"EMLINK          "<<EMLINK<<"   : Too many links. "<<'\n';
	cout <<"EROFS           "<<EROFS<<"   : Read-only file system."<<'\n';
	cout <<"EPIPE           "<<EPIPE<<"   : Broken pipe."<<'\n';
	cout <<"EDOM            "<<EDOM<<"   : Mathematics argument out of domain of function."<<'\n';
       	cout <<"ERANGE          "<<ERANGE<<"   : Result too large."<<'\n';
	cout <<"EDEADLK         "<<EDEADLK<<"   : Resource deadlock would occur. "<<'\n';
	cout <<"EDEADLOCK       "<<EDEADLOCK<<"   : On most architectures. info linux (man error)" <<'\n';
	cout <<"ENAMETOOLONG    "<<ENAMETOOLONG<<"   : Filename too long. "<<'\n';
	cout <<"ENOLCK          "<<ENOLCK<<"   : No locks available. "<<'\n';
	cout <<"ENOSYS          "<<ENOSYS<<"   : Functionality not supported."<<'\n';
	cout <<"ENOTEMPTY       "<<ENOTEMPTY<<"   : Directory not empty."<<'\n';
	cout <<"ELOOP           "<<ELOOP<<"   : Too many levels os symbolic links. "<<'\n';
	cout <<"ENOMSG          "<<ENOMSG<<"   : No message of the desired type."<<'\n';
	cout <<"EIDRM           "<<EIDRM<<"   : Identifier removed. "<<'\n';
	cout <<"ECHRNG          "<<ECHRNG<<"   : Channel number out of range."<<'\n';
	cout <<"EL2NSYNC        "<<EL2NSYNC<<"   : Level 2 not synchronized." << '\n';
	cout <<"EL3HLT          "<<EL3HLT<<"   : Level 3 halted. " << '\n';
	cout <<"EL3RST          "<<EL3RST<<"   : Level 3 halted." << '\n';
	cout <<"EUNATCH         "<<EUNATCH<<"   : Protocol driver not attached. " << '\n';
	cout <<"EL2HLT          "<<EL2HLT<<"   : Level 2 halted." << '\n';
	cout <<"EBADE           "<<EBADE<<"   : Ivaild exchange."<< '\n';
	cout <<"EBADR           "<<EBADR<<"   : Ivaild request descriptor."<< '\n';
	cout <<"EXFULL          "<<EXFULL<<"   : Exchange full. " << '\n';
	cout <<"ENOANO          "<<ENOANO<<"   : No andoe."<<'\n';
	cout <<"EBADRQC         "<<EBADRQC<<"   : Ivaild requset code."<<'\n';
	cout <<"EBADSLT         "<<EBADSLT<<"   : Invalid slot."<<'\n';
	cout <<"ENOSTR          "<<ENOSTR<<"   : Not a STREAM resources."<<'\n';
	cout <<"ENODATA         "<<ENODATA<<"   : No message is available on the STREAM head read queue."<<'\n';
	cout <<"ETIME           "<<ETIME<<"   : Stream ioctl() timeout. Tiemr expired."<<'\n';
	cout <<"ENOSR           "<<ENOSR<<"   : No STREAM resoureces."<<'\n';
	cout <<"ENONET          "<<ENONET<<"   : Machine is not on the network. "<<'\n';
	cout <<"ENOPKG          "<<ENOPKG<<"   : Package not installed. "<<'\n';
	cout <<"ENOLINK         "<<ENOLINK<<"   : Reserved."<<'\n';
	cout <<"ENOLINK         "<<ENOLINK<<"   : Reserved."<<'\n';
	cout <<"EREMOTE         "<<EREMOTE<<"   : Object is remote." <<'\n';
	cout <<"ECOMM           "<<ECOMM<<"   : Communication error on send."<<'\n';
	cout <<"EPROTO          "<<EPROTO<<"   : Protocol error."<<'\n';
	cout <<"EMULTIHOP       "<<EMULTIHOP<<"   : Multihop attempted. "<<'\n';
	cout <<"EOVERFLOW       "<<EOVERFLOW<<"   : Value too large to be stored in data type."<<'\n';
	cout <<"ENOTUNIQ        "<<ENOTUNIQ<<"   : Name not unique on network." <<'\n';
	cout <<"EBADFD          "<<EBADFD<<"   : File descriptor in bad state."<<'\n';
	cout <<"EREMCHG         "<<EREMCHG<<"   : Remote address changed."<<'\n';
	cout <<"ELIBACC         "<<ELIBACC<<"   : Cannot access a neede shared libaray"<<'\n';
	cout <<"ELIBBAD         "<<ELIBBAD<<"   : Accessing a corrupted shared libaray."<<'\n';
	cout <<"ELIBSCN         "<<ELIBSCN<<"   : .lib section in a.out corrupted" <<'\n';
	cout <<"ELIBMAX         "<<ELIBMAX<<"   : Attempting to link in too many shared libraries."<<'\n';
	cout <<"ELIBEXEC        "<<ELIBEXEC<<"   : Cannot exex a shared library directly." << '\n';
	cout <<"EILSEQ          "<<EILSEQ<<"   : Illegal byte sequence. "<<'\n';
	cout <<"ERESTART        "<<ERESTART<<"   : Interrupted system call should be restarted."<<'\n';
	cout <<"ESTRPIPE        "<<ESTRPIPE<<"   : Streams pipe error."<< '\n';
	cout <<"EUSERS          "<<EUSERS<<"   : Too many users." <<'\n';
	cout <<"ENOTSOCK        "<<ENOTSOCK<<"   : Not a socket."<<'\n'; 
	cout <<"EDESTADDRREQ    "<<EDESTADDRREQ<<"   : Destination address required. "<<'\n';
	cout <<"EMSGSIZE        "<<EMSGSIZE<<"   : Message too large."<<'\n';
	cout <<"EPROTOTYPE      "<<EPROTOTYPE<<"   : Protocol worng type for socket."<<'\n';
	cout <<"ENOPROTOOPT     "<<ENOPROTOOPT<<"   : Protocol not avalable."<<'\n';
	cout <<"EPROTONOSUPPORT "<<EPROTONOSUPPORT<<"   : Protocol not supported."<<'\n';
	cout <<"ESOCKTNOSUPPORT "<<ESOCKTNOSUPPORT<<"   : Socket type not supported."<<'\n';
	cout <<"ENOTSUP         "<<ENOTSUP<<"   : Operation Not supported (may be the same values as [EOPNOTSUPP])."<<'\n';
	cout <<"EPFNOSUPPORT    "<<EPFNOSUPPORT<<"   : Protocol family not supported."<<'\n';
	cout <<"EAFNOSUPPORT    "<<EAFNOSUPPORT<<"   : Address family not supported. "<<'\n';
	cout <<"EADDRINUSE      "<<EADDRINUSE<<"   : Address in user."<<'\n';
	cout <<"EADDRNOTAVAIL   "<<EADDRNOTAVAIL<<"   : Address not available."<<'\n'; 
	cout <<"ENETDOWN        "<<ENETDOWN<<"  : Network is down. "<<'\n';
	cout <<"ENETUNREACH     "<<ENETUNREACH<<"  : Network unreachable. "<<'\n';
	cout <<"ENETRESET       "<<ENETRESET<<"  : Connection aborted by network. "<<'\n';
	cout <<"ECONNABORTED    "<<ECONNABORTED<<"  : Connection aborted."<<'\n';
	cout <<"ECONNRESET      "<<ECONNRESET<<"  : Connection reset. "<<'\n';
	cout <<"ENOBUFS         "<<ENOBUFS<<"  : No buffer space available. "<<'\n';
	cout <<"EISCONN         "<<EISCONN<<"  : Socket is connected. "<<'\n';
	cout <<"ENOTCONN        "<<ENOTCONN<<"  : The socket is not connected."<<'\n';
	cout <<"ESHUTDOWN       "<<ESHUTDOWN<<"  : Cannot send after transport endpoint shutdown." <<'\n';
	cout <<"ETOOMANYREFS    "<<ETOOMANYREFS<<"  : Too many refrences: cannot splice."<<'\n';
	cout <<"ETIMEDOUT       "<<ETIMEDOUT<<"  : Connection timed out."<<'\n'; 
	cout <<"ECONNREFUSED    "<<ECONNREFUSED<<"  : Connection refused. "<<'\n';
	cout <<"EHOSTDOWN       "<<EHOSTDOWN<<"  : Host id down. " <<'\n';
	cout <<"EHOSTUNREACH    "<<EHOSTUNREACH<<"  : Host is unreachable. "<<'\n';
	cout <<"EALREADY        "<<EALREADY<<"  : Connection already in progress. "<<'\n';
	cout <<"EINPROGRESS     "<<EINPROGRESS<<"  : Operation in progress. "<<'\n';
	cout <<"ESTALE          "<<ESTALE<<"  : Stale file handle ."<<'\n';
	cout <<"EUCLEAN         "<<EUCLEAN<<"  : Structure needs cleaning." <<'\n';
	cout <<"EISNAM          "<<EISNAM<<"  : Is a named type file."<< '\n';
	cout <<"EREMOTEIO       "<<EREMOTEIO<<"  : Remote I/O error." <<'\n';
	cout <<"EDQOUT          "<<EDQUOT<<"  : Disk quota exceeded. "<<'\n';
	cout <<"ENOMEDIUM       "<<ENOMEDIUM<<"  : No medium found. "<<'\n';
	cout <<"EMEDIUMTYPE     "<<EMEDIUMTYPE<<"  : Wrong medium type."<<'\n';
	cout <<"ECANCELED       "<<ECANCELED<<"  : Operation canceled. "<<'\n';
	cout <<"ENOKEY          "<<ENOKEY<<"  : Required key not available."<<'\n';
	cout <<"EKEYEXPIRED     "<<EKEYEXPIRED<<"  : Key has expired."<<'\n';
	cout <<"EKEYREVOKED     "<<EKEYREVOKED<<"  : Key has been revoked." <<'\n';
	cout <<"EKEYREJECTED    "<<EKEYREJECTED<<"  : Key was rejected by service."<<'\n';
	cout <<"EOWNERDEAD      "<<EOWNERDEAD<<"  : Previous owner died. "<<'\n';
	cout <<"ENOTRECOVERABLE "<<ENOTRECOVERABLE<<"  : State not recoverable."<<'\n';
	cout <<"ERFKILL         "<<ERFKILL<<"  : Operation not possible due to RF-kill."<<'\n';
	cout <<"EHWPOISON       "<<EHWPOISON<<"  : Memory page has hardware error." <<'\n';
	

}

